In [1]:
import tensorflow as tf
import numpy as np
import re
from collections import Counter

In [2]:
corpus = """
I love deep learning.
Deep learning is amazing.
I love transformers.
Transformers are powerful.
Deep learning powers GPT.
GPT generates text.
"""

In [3]:
corpus = corpus.lower()

In [4]:
corpus = re.sub(r"[^\w\s]","",corpus)

In [5]:
tokens = corpus.split()

In [6]:
word_counts = Counter(tokens)

In [7]:
print(word_counts)

Counter({'deep': 3, 'learning': 3, 'i': 2, 'love': 2, 'transformers': 2, 'gpt': 2, 'is': 1, 'amazing': 1, 'are': 1, 'powerful': 1, 'powers': 1, 'generates': 1, 'text': 1})


In [8]:
vocab = {
    "<PAD>":0,
    "<UNK>":1
}

In [9]:
for word in word_counts:
  vocab[word] = len(vocab)

In [10]:
id_to_word = {id : word for word ,id in vocab.items()}

In [11]:
encoded = [vocab.get(word,vocab["<UNK>"]) for word in tokens]

In [12]:
print(encoded)

[2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 11, 12, 12, 13, 14]


In [13]:
inputs = []

targets = []

In [14]:
for i in range(1,len(encoded)):
  input_sequence = encoded[:i]
  target = encoded[i]
  inputs.append(input_sequence)
  targets.append(target)

In [15]:
print(inputs)

[[2], [2, 3], [2, 3, 4], [2, 3, 4, 5], [2, 3, 4, 5, 4], [2, 3, 4, 5, 4, 5], [2, 3, 4, 5, 4, 5, 6], [2, 3, 4, 5, 4, 5, 6, 7], [2, 3, 4, 5, 4, 5, 6, 7, 2], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 11], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 11, 12], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 11, 12, 12], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 11, 12, 12, 13]]


In [16]:
print(targets)

[3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 11, 12, 12, 13, 14]


In [17]:
max_length = max(len(sequence) for sequence in inputs)

In [18]:
print(max_length)

20


In [19]:
pad_id = vocab["<PAD>"]

In [20]:
padded_inputs = []

for sequence in inputs:

  if len(sequence) < max_length:

    sequence += [pad_id] * (max_length - len(sequence))

  padded_inputs.append(sequence)

In [21]:
print(padded_inputs)

[[2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 0, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 0, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 0, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 0, 0, 0, 0, 0], [2, 3, 4, 5, 4, 5, 6, 7, 2, 3, 8, 8, 9, 10, 4, 5, 0, 0, 0, 0], [2, 

In [22]:
input_tensor = tf.constant(
    padded_inputs, dtype = tf.int32
)

In [23]:
target_tensor = tf.constant(
    targets, dtype = tf.int32
)

In [24]:

print(input_tensor.shape)

print(target_tensor.shape)

(20, 20)
(20,)


In [25]:
print(input_tensor.numpy())

[[ 2  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  0  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  0  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  0  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  8  0  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  8  9  0  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  8  9 10  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  8  9 10  4  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  8  9 10  4  5  0  0

In [26]:
print(target_tensor.numpy())

[ 3  4  5  4  5  6  7  2  3  8  8  9 10  4  5 11 12 12 13 14]


In [27]:
attention_mask = tf.cast(tf.not_equal(
    input_tensor,pad_id
)
,
tf.int32)

In [28]:
dataset = tf.data.Dataset.from_tensor_slices(
    (
        {"input_ids":input_tensor,
         "attention_mask":attention_mask},
        target_tensor
    )
)

In [29]:
dataset = dataset.shuffle(buffer_size = len(input_tensor))

In [30]:
batch_size = 4

dataset = dataset.batch(batch_size)

In [31]:
dataset = dataset.prefetch(
    tf.data.AUTOTUNE
)

In [32]:
for batch_inputs, batch_targets in dataset.take(1):
  print(batch_inputs["input_ids"])
  print(batch_inputs["attention_mask"])
  print(batch_targets)

tf.Tensor(
[[ 2  3  4  5  4  5  6  7  2  3  8  8  9 10  4  5  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  8  9 10  0  0  0  0  0  0]
 [ 2  3  4  5  4  5  6  7  2  3  8  0  0  0  0  0  0  0  0  0]
 [ 2  3  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]], shape=(4, 20), dtype=int32)
tf.Tensor(
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]], shape=(4, 20), dtype=int32)
tf.Tensor([11  4  8  4], shape=(4,), dtype=int32)


In [33]:
vocab_size = len(vocab)

embedding_dim = 64

max_size = input_tensor.shape[1]

In [34]:
print(vocab_size)

15


In [35]:
token_embeddings = tf.keras.layers.Embedding(

   input_dim = vocab_size,

   output_dim = embedding_dim

)

In [36]:
token_embedding = token_embeddings(input_tensor)

In [37]:
position_embedding = tf.keras.layers.Embedding(

    input_dim = max_length,

    output_dim = embedding_dim

)

In [38]:
positions = tf.range(max_length)

In [39]:
print(positions)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19], shape=(20,), dtype=int32)


In [40]:
positional_embedding = position_embedding(positions)

In [41]:
print(token_embedding.shape)

print(positional_embedding.shape)

(20, 20, 64)
(20, 64)


In [42]:
positional_embedding = tf.expand_dims(
    positional_embedding,
    axis=0
)

In [43]:
print(positional_embedding.shape)

(1, 20, 64)


In [44]:
embeddings = token_embedding + positional_embedding

In [45]:
print(embeddings.shape)

(20, 20, 64)


In [46]:
embedding_dim = 64

#query = tf.keras.layers.Dense(embedding_dim)
#key = tf.keras.layers.Dense(embedding_dim)
##value = tf.keras.layers.Dense(embedding_dim)

In [47]:
#query_layer = query(embeddings)
#key_layer = key(embeddings)
#value_layer = value(embeddings)

In [48]:
#print(query_layer.shape)
#print(key_layer.shape)
#print(value_layer.shape)

In [49]:
#scores = tf.matmul(query_layer,key_layer,transpose_b = True)

In [50]:
#print(scores)

In [51]:
#print(scores.shape)

In [52]:
#import math

#dk = tf.cast(key_layer.shape[-1],tf.float32)

#scores = scores/math.sqrt(dk)

In [53]:
#print(scores)

In [54]:
#print(scores.shape)

In [55]:
#sequence_length = tf.shape(embeddings)[1]

#mask = tf.linalg.band_part(
    #tf.ones((sequence_length,sequence_length)),
    #-1,
    #0
#)

In [56]:
#mask = tf.expand_dims(
    #mask,
    #axis=0,
#)

In [57]:
#print(mask)

In [58]:
#scores = tf.where(
    #mask == 0,
    #-1e9,
    #scores
#)

In [59]:
#attention_weights = tf.nn.softmax(
    #scores,
    #axis=-1
#)

In [60]:
#attention_output = tf.matmul(
    #attention_weights,
    #value_layer
#)

In [61]:
#print(attention_output)

In [62]:
#print(attention_output.shape)

In [63]:
num_heads = 4

head_dim = embedding_dim // num_heads

In [64]:
query_layer = tf.keras.layers.Dense(embedding_dim)

key_layer = tf.keras.layers.Dense(embedding_dim)

value_layer = tf.keras.layers.Dense(embedding_dim)

In [65]:
Q = query_layer(embeddings)

K = key_layer(embeddings)

V = value_layer(embeddings)

In [66]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 64)
(20, 20, 64)
(20, 20, 64)


In [67]:
batch_size = tf.shape(embeddings)[0]

sequence_length = tf.shape(embeddings)[1]


In [68]:
Q = tf.reshape(
    Q,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [69]:
K = tf.reshape(
    K,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [70]:
V = tf.reshape(
    V,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [71]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 4, 16)
(20, 20, 4, 16)
(20, 20, 4, 16)


In [72]:
Q = tf.transpose(
    Q,
    perm = [0,2,1,3]
)

In [73]:
K = tf.transpose(
    K,
    perm = [0,2,1,3]
)

In [74]:
V = tf.transpose(
    V,
    perm = [0,2,1,3]
)

In [75]:
scores = tf.matmul(
    Q,
    K,
    transpose_b = True
)

In [76]:
#print(scores)

In [77]:
scores = scores / tf.math.sqrt(
    tf.cast(head_dim,tf.float32)
)

In [78]:
mask = tf.linalg.band_part(
    tf.ones(
        (sequence_length,
        sequence_length)
    ),
    -1,
    0
)

In [79]:
mask = tf.expand_dims(mask,axis=0)

In [80]:
mask = tf.expand_dims(mask,axis=0)

In [81]:
print(mask.shape)

(1, 1, 20, 20)


In [82]:
print(scores.shape)

(20, 4, 20, 20)


In [83]:
scores = tf.where(
    mask == 0,
    -1e9,
    scores
)

In [84]:
attention_weights = tf.nn.softmax(
    scores,
    axis = -1
)

In [85]:
attention = tf.matmul(
    attention_weights,
    V
)

In [86]:
print(attention.shape)

(20, 4, 20, 16)


In [87]:
attention = tf.transpose(
    attention,
    perm = [0,2,1,3]
)

In [88]:
attention = tf.reshape(
    attention,
    (batch_size,
     sequence_length,
     embedding_dim)
)

In [89]:
output_layer = tf.keras.layers.Dense(embedding_dim)

In [90]:
multi_head_output = output_layer(attention)

In [91]:
print(multi_head_output.shape)

(20, 20, 64)


In [92]:
residual = multi_head_output

In [93]:
layer_norm1 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)

attention_output = layer_norm1(
    residual + multi_head_output
)

In [94]:
ffn_dim = embedding_dim * 4

In [95]:
dense1 = tf.keras.layers.Dense(
    ffn_dim,
    activation = "gelu"
)

In [96]:
dense2 = tf.keras.layers.Dense(embedding_dim)

In [97]:
ffn_output = dense1(attention_output)

ffn_output = dense2(ffn_output)

In [98]:
residual = attention_output

In [99]:
ffn_output = ffn_output + residual

In [100]:
layer_norm2 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)


decoder_output = layer_norm2(ffn_output)

In [101]:
print(decoder_output.shape)

(20, 20, 64)


DECODER BLOCK 2

In [102]:
embeddings = decoder_output

print(embeddings.shape)

(20, 20, 64)


In [103]:
embedding_dim = 64

In [104]:
num_heads = 4

head_dim = embedding_dim // num_heads

In [105]:
query_layer = tf.keras.layers.Dense(embedding_dim)

key_layer = tf.keras.layers.Dense(embedding_dim)

value_layer = tf.keras.layers.Dense(embedding_dim)

In [106]:
Q = query_layer(embeddings)

K = key_layer(embeddings)

V = value_layer(embeddings)

In [107]:
batch_size = tf.shape(embeddings)[0]

sequence_length = tf.shape(embeddings)[1]

In [108]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 64)
(20, 20, 64)
(20, 20, 64)


In [109]:
Q = tf.reshape(
    Q,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [110]:
K = tf.reshape(
    K,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [111]:
V = tf.reshape(
    V,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [112]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 4, 16)
(20, 20, 4, 16)
(20, 20, 4, 16)


In [113]:
Q = tf.transpose(
    Q,
    perm = [0,2,1,3]
)

In [114]:
K = tf.transpose(
    K,
    perm = [0,2,1,3]
)

In [115]:
V = tf.transpose(
    V,
    perm = [0,2,1,3]
)

In [116]:
scores = tf.matmul(
    Q,
    K,
    transpose_b = True
)

In [117]:
#print(scores)

In [118]:
scores = scores / tf.math.sqrt(
    tf.cast(head_dim,tf.float32)
)

In [119]:
mask = tf.linalg.band_part(
    tf.ones(
        (sequence_length,
        sequence_length)
    ),
    -1,
    0
)

In [120]:
mask = tf.expand_dims(mask,axis=0)

In [121]:
mask = tf.expand_dims(mask,axis=0)

In [122]:
print(mask.shape)

(1, 1, 20, 20)


In [123]:
print(scores.shape)

(20, 4, 20, 20)


In [124]:
scores = tf.where(
    mask == 0,
    -1e9,
    scores
)

In [125]:
attention_weights = tf.nn.softmax(
    scores,
    axis = -1
)

In [126]:
attention = tf.matmul(
    attention_weights,
    V
)

In [127]:
print(attention.shape)

(20, 4, 20, 16)


In [128]:
attention = tf.transpose(
    attention,
    perm = [0,2,1,3]
)

In [129]:
attention = tf.reshape(
    attention,
    (batch_size,
     sequence_length,
     embedding_dim)
)

In [130]:
output_layer = tf.keras.layers.Dense(embedding_dim)

In [131]:
multi_head_output = output_layer(attention)

In [132]:
print(multi_head_output.shape)

(20, 20, 64)


In [133]:
residual = multi_head_output

In [134]:
layer_norm1 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)

attention_output = layer_norm1(
    residual + multi_head_output
)

In [135]:
ffn_dim = embedding_dim * 4

In [136]:
dense1 = tf.keras.layers.Dense(
    ffn_dim,
    activation = "gelu"
)

In [137]:
dense2 = tf.keras.layers.Dense(embedding_dim)

In [138]:
ffn_output = dense1(attention_output)

ffn_output = dense2(ffn_output)

In [139]:
residual = attention_output

In [140]:
ffn_output = ffn_output + residual

In [141]:
layer_norm2 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)


decoder_output = layer_norm2(ffn_output)

In [142]:
print(decoder_output.shape)

(20, 20, 64)


**DECODER BLOCK 3**

In [143]:
embeddings = decoder_output

In [144]:
print(embeddings.shape)

(20, 20, 64)


In [145]:
embedding_dim = 64

In [146]:
num_heads = 4

head_dim = embedding_dim // num_heads

In [147]:
query_layer = tf.keras.layers.Dense(embedding_dim)

key_layer = tf.keras.layers.Dense(embedding_dim)

value_layer = tf.keras.layers.Dense(embedding_dim)

In [148]:
Q = query_layer(embeddings)

K = key_layer(embeddings)

V = value_layer(embeddings)

In [149]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 64)
(20, 20, 64)
(20, 20, 64)


In [150]:
batch_size = tf.shape(embeddings)[0]

sequence_length = tf.shape(embeddings)[1]


In [151]:
Q = tf.reshape(
    Q,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [152]:
K = tf.reshape(
    K,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [153]:
V = tf.reshape(
    V,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [154]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 4, 16)
(20, 20, 4, 16)
(20, 20, 4, 16)


In [155]:
Q = tf.transpose(
    Q,
    perm = [0,2,1,3]
)

In [156]:
K = tf.transpose(
    K,
    perm = [0,2,1,3]
)

In [157]:
V = tf.transpose(
    V,
    perm = [0,2,1,3]
)

In [158]:
scores = tf.matmul(
    Q,
    K,
    transpose_b = True
)

In [159]:
#print(scores)

In [160]:
scores = scores / tf.math.sqrt(
    tf.cast(head_dim,tf.float32)
)

In [161]:
mask = tf.linalg.band_part(
    tf.ones(
        (sequence_length,
        sequence_length)
    ),
    -1,
    0
)

In [162]:
mask = tf.expand_dims(mask,axis=0)

In [163]:
mask = tf.expand_dims(mask,axis=0)

In [164]:
print(mask.shape)

(1, 1, 20, 20)


In [165]:
print(scores.shape)

(20, 4, 20, 20)


In [166]:
scores = tf.where(
    mask == 0,
    -1e9,
    scores
)

In [167]:
attention_weights = tf.nn.softmax(
    scores,
    axis = -1
)

In [168]:
attention = tf.matmul(
    attention_weights,
    V
)

In [169]:
print(attention.shape)

(20, 4, 20, 16)


In [170]:
attention = tf.transpose(
    attention,
    perm = [0,2,1,3]
)

In [171]:
attention = tf.reshape(
    attention,
    (batch_size,
     sequence_length,
     embedding_dim)
)

In [172]:
output_layer = tf.keras.layers.Dense(embedding_dim)

In [173]:
multi_head_output = output_layer(attention)

In [174]:
print(multi_head_output.shape)

(20, 20, 64)


In [175]:
residual = multi_head_output

In [176]:
layer_norm1 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)

attention_output = layer_norm1(
    residual + multi_head_output
)

In [177]:
ffn_dim = embedding_dim * 4

In [178]:
dense1 = tf.keras.layers.Dense(
    ffn_dim,
    activation = "gelu"
)

In [179]:
dense2 = tf.keras.layers.Dense(embedding_dim)

In [180]:
ffn_output = dense1(attention_output)

ffn_output = dense2(ffn_output)

In [181]:
residual = attention_output

In [182]:
ffn_output = ffn_output + residual

In [183]:
layer_norm2 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)


decoder_output = layer_norm2(ffn_output)

In [184]:
print(decoder_output.shape)

(20, 20, 64)


**DECODER BLOCK 4**

In [185]:
embeddings = decoder_output

In [186]:
print(embeddings.shape)

(20, 20, 64)


In [187]:
embedding_dim = 64

In [188]:
num_heads = 4

head_dim = embedding_dim // num_heads

In [189]:
query_layer = tf.keras.layers.Dense(embedding_dim)

key_layer = tf.keras.layers.Dense(embedding_dim)

value_layer = tf.keras.layers.Dense(embedding_dim)

In [190]:
Q = query_layer(embeddings)

K = key_layer(embeddings)

V = value_layer(embeddings)

In [191]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 64)
(20, 20, 64)
(20, 20, 64)


In [192]:
batch_size = tf.shape(embeddings)[0]

sequence_length = tf.shape(embeddings)[1]


In [193]:
Q = tf.reshape(
    Q,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [194]:
K = tf.reshape(
    K,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [195]:
V = tf.reshape(
    V,
    (batch_size,
     sequence_length,
     num_heads,
     head_dim)
)

In [196]:
print(Q.shape)
print(K.shape)
print(V.shape)

(20, 20, 4, 16)
(20, 20, 4, 16)
(20, 20, 4, 16)


In [197]:
Q = tf.transpose(
    Q,
    perm = [0,2,1,3]
)

In [198]:
K = tf.transpose(
    K,
    perm = [0,2,1,3]
)

In [199]:
V = tf.transpose(
    V,
    perm = [0,2,1,3]
)

In [200]:
scores = tf.matmul(
    Q,
    K,
    transpose_b = True
)

In [201]:
#print(scores)

In [202]:
scores = scores / tf.math.sqrt(
    tf.cast(head_dim,tf.float32)
)

In [203]:
mask = tf.linalg.band_part(
    tf.ones(
        (sequence_length,
        sequence_length)
    ),
    -1,
    0
)

In [204]:
mask = tf.expand_dims(mask,axis=0)

In [205]:
mask = tf.expand_dims(mask,axis=0)

In [206]:
print(mask.shape)

(1, 1, 20, 20)


In [207]:
print(scores.shape)

(20, 4, 20, 20)


In [208]:
scores = tf.where(
    mask == 0,
    -1e9,
    scores
)

In [209]:
attention_weights = tf.nn.softmax(
    scores,
    axis = -1
)

In [210]:
attention = tf.matmul(
    attention_weights,
    V
)

In [211]:
print(attention.shape)

(20, 4, 20, 16)


In [212]:
attention = tf.transpose(
    attention,
    perm = [0,2,1,3]
)

In [213]:
attention = tf.reshape(
    attention,
    (batch_size,
     sequence_length,
     embedding_dim)
)

In [214]:
output_layer = tf.keras.layers.Dense(embedding_dim)

In [215]:
multi_head_output = output_layer(attention)

In [216]:
print(multi_head_output.shape)

(20, 20, 64)


In [217]:
residual = multi_head_output

In [218]:
layer_norm1 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)

attention_output = layer_norm1(
    residual + multi_head_output
)

In [219]:
ffn_dim = embedding_dim * 4

In [220]:
dense1 = tf.keras.layers.Dense(
    ffn_dim,
    activation = "gelu"
)

In [221]:
dense2 = tf.keras.layers.Dense(embedding_dim)

In [222]:
ffn_output = dense1(attention_output)

ffn_output = dense2(ffn_output)

In [223]:
residual = attention_output

In [224]:
ffn_output = ffn_output + residual

In [225]:
layer_norm2 = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)


decoder_output = layer_norm2(ffn_output)

In [226]:
print(decoder_output.shape)

(20, 20, 64)


In [227]:
final_layer_norm = tf.keras.layers.LayerNormalization(
    epsilon = 1e-6
)

decoder_output = final_layer_norm(decoder_output)

In [228]:
lm_head = tf.keras.layers.Dense(
    vocab_size
)

logits = lm_head(decoder_output)

In [229]:
print(logits.shape)

(20, 20, 15)


In [230]:
print(logits)

tf.Tensor(
[[[-1.9393957  -1.6985309  -0.4199694  ...  1.0309918  -0.10694739
   -0.693382  ]
  [-1.6571624  -1.2710521  -0.38352385 ...  0.78111905  0.10520637
   -0.95792794]
  [-1.4084303  -0.9438737  -0.36389711 ...  0.55832684  0.27898005
   -1.1468912 ]
  ...
  [-1.1640751   0.34006703 -0.23189466 ... -0.05254342  0.42030105
   -1.8941915 ]
  [-1.1689582   0.38624915 -0.22266406 ... -0.0723266   0.4144982
   -1.9151721 ]
  [-1.172237    0.431741   -0.21299571 ... -0.09226137  0.40800127
   -1.934383  ]]

 [[-1.9393957  -1.6985309  -0.4199694  ...  1.0309918  -0.10694739
   -0.693382  ]
  [-1.8385825  -1.5739157  -0.27925998 ...  0.93498033 -0.02867234
   -0.9463349 ]
  [-1.7250088  -1.4320828  -0.16900872 ...  0.8285406   0.06102078
   -1.1507821 ]
  ...
  [-1.707514   -0.56621987  0.46357262 ...  0.21220958  0.12135275
   -2.081359  ]
  [-1.730832   -0.5360929   0.48020542 ...  0.18302464  0.113811
   -2.1134548 ]
  [-1.7530267  -0.5049293   0.4958688  ...  0.15299547  0.1062966

In [231]:
probabilities = tf.nn.softmax(
    logits,
    axis = -1
)

In [232]:
predicted_tokens = tf.argmax(
    probabilities,
    axis = -1
)

In [233]:
print(predicted_tokens.shape)

(20, 20)


In [234]:
generated_sentences = []

for sentence in predicted_tokens.numpy():

  words=[]

  for token in sentence:

    words.append(id_to_word[token])

  generated_sentences.append(word)

print(generated_sentences)

['text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text', 'text']


In [235]:
loss_function = tf.keras.losses.SparseCategoricalCrossentropy(
    from_logits = True
)

In [236]:
optimizer = tf.keras.optimizers.Adam(
    learning_rate = 1e-4
)